### ISSUE TITLE
어드민 페이지 Build오류 수정

### ISSUE THREAD

**Issue by blue7918** [TeamProject-Farmer/front-end#10]
## Description
어드민 페이지 빌드 오류가 나는 이유 해결

## Todo
- [x] vscode terminal git bash로 설정
- [x] git branch 동기화
- [x] folder 이름 수정안되는 문제 해결
- [x] 어드민 페이지 build 오류 안나게 수정 후 PR

## ETC
git ignore 파일 수정 필요

**Comment by hyeone999** [comment]
화이팅!!! 🔋
