### ISSUE TITLE
[Board] 어드민 게시판 페이지 UI 작업

### ISSUE THREAD

**Issue by blue7918** [TeamProject-Farmer/front-end#110]
## Description
게시판 페이지 UI 작업

## Todo
- [ ] 게시글 조회 부분
- [ ] 게시글 조회 관리 부분
- [x] AdminLayout 삭제 및 그에 따른 세부 작업 추가
- [x] Home 부분 파일 위치 리펙토링
