### ISSUE TITLE
[StyleComponent] 관리자 페이지 UI 작업

### ISSUE THREAD

**Issue by zwonkim** [TeamProject-Farmer/front-end#111]
## Description
admin 페이지의 UI 작업을 진행합니다

## Todo
- [ ] 주문 페이지 ui 작업
- [ ] 회원 페이지 ui 작업
- [ ] 프로모션 페이지 ui 작업
