### ISSUE TITLE
어드민UI 리펙토링

### ISSUE THREAD

**Issue by blue7918** [TeamProject-Farmer/front-end#17]
## Description
PR에서 요청해주신 부분들 수정 및 리펙토링

## Todo
- [ ] function -> arrow function
- [ ] type file 따로 생성 후 import
- [ ] Modal 공통된 부분 따로 컴포넌트 생성
- [ ] BoardInnerBox 부분 수정
- [ ] 스크롤 방지 부분 document.body 외 다른 방식 사용하기
- [ ] 전체적으로 리펙토링
