### ISSUE TITLE
회원가입 변경사항 구현

### ISSUE THREAD

**Issue by hyeone999** [TeamProject-Farmer/front-end#20]
## Description
회원가입 변경사항 구현

## Todo
- [x] 회원가입 성공시 로그인 페이지로 route
- [x] 회원가입 페이지 변경된 디자인 적용
- [x] 이메일 셀렉창 디자인 수정 요청
