### ISSUE TITLE
회원가입 페이지 변경사항 반영(UI 및 API)

### ISSUE THREAD

**Issue by hyeone999** [TeamProject-Farmer/front-end#26]
## Description
기획 변경에 따른 회원가입 페이지 변경사항 반영(UI 및 API)

## Todo
- [x] 회원가입시 유저에게 입력 받는 정보 변경 (닉네임, 이메일, 비밀번호만 입력받음)
- [x] 해당 정보 변경에 따른 API 수정
- [x] 해당 정보 변경에 따른 UI 수정

## ETC
- 아직 백엔드 배포 안된 상태(대기중)
- 디자인팀에서 디자인 다시 그려주셔야함(대기중)
