### ISSUE TITLE
샵 UI 수정

### ISSUE THREAD

**Issue by blue7918** [TeamProject-Farmer/front-end#43]
## Description
상세페이지 UI 수정 및 일부 기능 수정

## Todo
- [x] 옵션 추가 부분 - 리스트가 계속 쌓이는 부분 수정
- [x] 리뷰 부분 - 내구성, 가격, etc 개별 별점 삭제
- [x] navbar 부분 - width 다시 설정
- [x] 상품 card 부분 - 배치, 상세 css 추가 수정
- [x] 페이지 이동 링크 추가

## ETC
수정 후 pr 올리기
