### ISSUE TITLE
검색 페이지 API 구현

### ISSUE THREAD

**Issue by zwonkim** [TeamProject-Farmer/front-end#50]
## Todo
- [ ] 최근 검색 데이터 불러오기 (비회원일 경우 조건 처리)
- [ ] 검색한 상품 목록 출력
- [ ] 검색 카테고리 별 상품 출력
