### ISSUE TITLE
검색페이지 조건처리 및 오류 수정

### ISSUE THREAD

**Issue by zwonkim** [TeamProject-Farmer/front-end#66]
## Todo
- [ ] 검색 결과가 없는 경우에 대한 조건 처리
- [ ] 검색 결과 정렬 옵션이 바뀔 때에 대한 조건부 스타일링 추가
- [ ] 검색 결과 컨텐츠 이미지 오류 수정
