### ISSUE TITLE
메인 페이지 수정된 디자인 반영

### ISSUE THREAD

**Issue by zwonkim** [TeamProject-Farmer/front-end#67]
## Todo
- [ ] 추가된 메뉴바 기능 구현(모달)
- [ ] 변경된 shopBySize 디자인 반영
- [ ] bestPlant 무한 슬라이더 수정
