### ISSUE TITLE
메인 페이지 기능 구현

### ISSUE THREAD

**Issue by zwonkim** [TeamProject-Farmer/front-end#7]
## Description
이벤트, 슬라이더 등 메인페이지에서 구현해야할 기능 추가하기

## Todo
- [x] 프로젝트 생성
- [x] 메인 페이지 변경된 디자인 반영
- [ ] 메인 페이지 기능 구현
- [x] 로그인 파트 코드 리뷰
