### ISSUE TITLE
메인페이지 마무리 작업

### ISSUE THREAD

**Issue by blue7918** [TeamProject-Farmer/front-end#72]
## Description
- 기능들이 잘 작동하는지 테스트
- 카테고리 관련 url 변경

## Todo
- [x] 본인이 구현한 페이지에 대한 권한별 라우팅 처리 (회원만 접근, 비회원만 접근, 모두 접근 가능)
- [x] url 변경 및 카테고리 관련 코드 수정
- [x] review 좋아요 부분 수정

## ETC
- 라우트 부분: 장바구니, 구매하기 제외 회원이여야만 하는 문의작성하기 버튼, 내가 쓴 문의 버튼 클릭 시 login 페이지로 이동하도록 처리해두었습니다.
- shop/[catedory]/detail/[productId] -> shop/detail/[productId]
- review 좋아요 부분은 좋아요 post를 한 즉시 review 데이터를 호출하면 해당 데이터(방금 누른 좋아요)가 적용되지 않은 상태로 호출 되기 때문에 약간의 시간 후에 다시 데이터를 호출해주는 방식으로 처리했습니다.
